AllCops:
  Exclude:
    - 'bin/cucumber'
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/rspec'
    - 'bin/spring'
    - 'db/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/models/account.rb'
    - 'app/models/user.rb'

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 100
  AllowURI: true
  Exclude:
    - 'bin/vagrant'
    - 'features/**/*'
    - 'lib/tasks/cucumber.rake'
    - 'spec/views/users/versions/index.html.haml_spec.rb'

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Style/DoubleNegation:
  Enabled: false
