# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e7dbda7cf1ef64c8abfa4f7159a100c986912c4850c5b0e6fff589d49c2daaef8f90f0b7039a22fd6ebcde8eec537b2d01d578c3d620099bc8d9dc52e333128

test:
  secret_key_base: 9c20005d9d15140f950acc3d1e4ba0dc4f7d73845a9ff42c75bad22b752b8b9ea28f290b65582ca795ba4848cf781d1096ffd669f020430e40fe9cbbb40ecc10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
