# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development: &development
  secret_key_base: 7d3da7d86a58ab7a7ed4817ec46b58e380811b8f7f9ee31e8197ab4e70b7d87b535d5fb89d13cc78266c9d94d1ed7c8dffa56369796a3b7f43b0ec082cbeb1bb
  devise_secret_key: '0724d3936095acd5e5a17fa5c92983c71e4bda30c5fdb19cfcff954c31c97147a964b5d6905c96b24697f885bc20d654dcb5b17a44c7dd51022593faa5a0531e'

  omniauth: &omniauth-development
    # omniauth-facebook
    facebook_app_id: FACEBOOK_APP_ID
    facebook_app_secret: FACEBOOK_APP_SECRET
    # omniauth-github
    github_client_id: GITHUB_CLIENT_ID
    github_cient_secret: GITHUB_CLIENT_SECRET
    # omniauth-google-oauth2
    google_client_id: GOOGLE_CLIENT_ID
    google_client_secret: GOOGLE_CLIENT_SECRET
    # omniauth-twitter
    twitter_consumer_key: TWITTER_CONSUMER_KEY
    twitter_consumer_secret: TWITTER_CONSUMER_SECRET

  accounts_email_address: accounts@pleaseignore.com
  contact_email_address: contact@pleaseignore.com
  support_email_address: support@pleaseignore.com

  google_analytics: {}

test:
  <<: *development

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # Devise Setup
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>

  # Redis Setup
  redis_url: <%= ENV['REDIS_URL'] %>

  # Omniauth Setup
  omniauth:
    # omniauth-facebook
    facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
    facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
    # omniauth-github
    github_client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
    github_cient_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>
    # omniauth-google-oauth2
    google_client_id: <%= ENV['GOOGLE_CLIENT_ID'] %>
    google_client_secret: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
    # omniauth-twitter
    twitter_consumer_key: <%= ENV['TWITTER_CONSUMER_KEY'] %>
    twitter_consumer_secret: <%= ENV['TWITTER_CONSUMER_SECRET'] %>

  # Assets
  asset_host: <%= ENV["ASSET_HOST"] %>

  # HTTP Public Key Pinning
  hpkp_primary_key: <%= ENV['HPKP_PRIMARY_KEY'] %>
  hpkp_backup_key: <%= ENV['HPKP_BACKUP_KEY'] %>

  # Application Email Addresses
  accounts_email_address: <%= ENV["ACCOUNTS_EMAIL_ADDRESS"] %>
  contact_email_address: <%= ENV["CONTACT_EMAIL_ADDRESS"] %>
  support_email_address: <%= ENV["SUPPORT_EMAIL_ADDRESS"] %>

  # Google Analytics Setup
  google_analytics:
    analytics_id: <%= ENV["GOOGLE_ANALYTICS_ID"] %>

  # Rollbar Access Token
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
