# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d3da7d86a58ab7a7ed4817ec46b58e380811b8f7f9ee31e8197ab4e70b7d87b535d5fb89d13cc78266c9d94d1ed7c8dffa56369796a3b7f43b0ec082cbeb1bb
  accounts_email_address: accounts@pleaseignore.com
  contact_email_address: contact@pleaseignore.com
  support_email_address: support@pleaseignore.com

test:
  secret_key_base: 904a788dc72220294745b1a52c29119340d81316eca33ab3cf76ab22a9d1874059e4b2c7452dfea356c4519e5a128a65ddc2b00280110c0e4bc68c63e4da936b
  accounts_email_address: accounts@pleaseignore.com
  contact_email_address: contact@pleaseignore.com
  support_email_address: support@pleaseignore.com

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  accounts_email_address: <%= ENV["ACCOUNTS_EMAIL_ADDRESS"] %>
  contact_email_address: <%= ENV["CONTACT_EMAIL_ADDRESS"] %>
  support_email_address: <%= ENV["SUPPORT_EMAIL_ADDRESS"] %>
