---
:concurrency: <%= ENV.fetch('SIDEKIQ_WORKERS', 25).to_i %>
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:queues:
  - [default, 3]
  - [mailer, 2]
  - [high_priority, 5]
  - [low_priority, 1]
