AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'db/migrate/**/*.rb'
    - 'spec/dummy/**/*.rb'

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 100
  AllowURI: true

Style/AsciiComments:
  Exclude:
    - 'lib/core_extensions/string/safe_permalink.rb'
    - 'lib/core_extensions/string/transliterations.rb'
